### ISSUE TITLE
The download link for Baidu Mall dataset has expired. 

### ISSUE THREAD

**Issue by ssmem** [jinyummiao/map-in-mono-reloc#1]
Can you help me? Many thanks.

**Comment by jinyummiao** [comment]
The results in Baidu Mall dataset are directly cited from AnyLoc [1], its public [repository](https://github.com/AnyLoc/AnyLoc) has an available download link for Baidu Mall dataset. Hope this can help you.

[1] Keetha, Nikhil Varma et al. “AnyLoc: Towards Universal Visual Place Recognition.” ArXiv abs/2308.00688 (2023): n. pag.
